{{- if .Values.frontend.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  labels:
    app: guestbook
  annotations:
    metadata.annotations.kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
  {{- end }}