apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  type: {{ .Values.redis.slave.service.type }}
  ports:
    - port: {{ .Values.redis.slave.service.port }}
  selector:
    app: redis
    role: slave
    tier: backend