apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: {{ .Values.redis.master.service.type }}
  ports:
    - port: {{ .Values.redis.master.service.port }}
      targetPort: {{ .Values.redis.master.service.port }}
  selector:
    app: redis
    role: master
    tier: backend